### ISSUE TITLE
Resize call in inline transcript causes jumps in the page

### ISSUE THREAD

**Issue by simondate** [adaptlearning/adapt-vimeo#14]
When the learner clicks the inline transcript button it causes them to jump up the page. See below.

![chrome_gqvZsxFftx](https://user-images.githubusercontent.com/1676635/153464712-e6c2c69f-5014-4fc2-ae5f-fb6bfa27d5be.gif)

I haven't been able to replicate this with the Youtube or Vimeo component.

I found that the issue didn't occur if I comment out [this line of code](https://github.com/adaptlearning/adapt-vimeo/blob/master/js/TranscriptView.js#L49).

EDIT - According to the client, this only happens when a narrative is used before.

**Comment by simondate** [comment]
I just found out that this only happens when a narrative is used before.

**Comment by chris-steele** [comment]
Narrative seems to cause jumping issues in other circumstances: https://github.com/adaptlearning/adapt-contrib-narrative/issues/231

**Comment by oliverfoster** [comment]
this has since been resolved, appears to have been a narrative issue

![vimeo-jump](https://user-images.githubusercontent.com/7974663/230031185-2d67eb7a-33ef-486b-b611-83c2bdf8d327.gif)
