### ISSUE TITLE
Videos not completing, player stops working

### ISSUE THREAD

**Issue by marissa-champions** [adaptlearning/adapt-vimeo#21]
Occassionally, videos stop a few seconds before completion and log the error below. When completion is set to ended, the component does not get marked as complete.

### Your environment
* AT 0.10.5/Framework 5.17.2
* Occuring in Chrome(103.0.5060.114) and Safari 14.1 (Possibly others as well)
* iOS, MacOS, Windows

### Steps to reproduce
Insert video into course. View course. Play video.

### Expected behaviour
Videos should play to completion and then the component should be marked as complete.

### Actual behaviour
Video stops playing, component is not marked complete, player stops working

### Screenshots (if you can)
<img width="2347" alt="Screen Shot 2022-07-27 at 4 43 45 PM" src="https://user-images.githubusercontent.com/60671690/181381121-bab593a8-6438-4d8a-b54a-00be015d974b.png">

**Comment by chris-steele** [comment]
@marissa-champions I'm not currently able to replicate the issue. Has it continued to be a problem for you? Are there any particular video sources that cause the problem more than others? Any additional info you can provide to help us replicate the problem would be greatly appreciated.

**Comment by oliverfoster** [comment]
close stale
